from turtle import *
import turtle as tur
def rectangle(color):
    turt.begin_fill()
    turt.fillcolor(color)
    for i in range(2):
        turt.forward(400)
        turt.right(90)
        turt.forward(100)
        turt.right(90)
    turt.end_fill()

turt=tur.Turtle()
tur.screensize(500,400)
tur.title("Pythontpoint")
turt.up()
turt.pensize(4)
turt.goto(0,-300)
turt.down()
turt.goto(0,400)
rectangle("orange")
turt.goto(0,300)
turt.forward(200)
turt.color("blue")
turt.circle(-50)
turt.setheading(270)
turt.forward(50)
turt.setheading(0)
for i in range(24):
    turt.forward(45)
    turt.bk(45)
    turt.left(15)
turt.setheading(90)
turt.forward(50)
turt.setheading(0)
turt.color("black")
turt.forward(200)
turt.right(90)
turt.forward(100)
turt.right(90)
turt.forward(400)
turt.right(90)
turt.forward(100)
turt.right(90)
turt.goto(0,200)
rectangle("green")
tur.done()